M48
; DRILL file {KiCad (6.0.4)} date Thu Apr 28 11:38:30 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-04-28T11:38:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.7028Y-1.7933
X3.7028Y-3.7224
X5.9862Y-1.7933
X5.9862Y-3.7224
T0
M30
